#!/bin/bash
python experiments/train.py -c baselines/NLinear/ETTh1.py --gpus '0'
python experiments/train.py -c baselines/NLinear/ETTh2.py --gpus '0'
python experiments/train.py -c baselines/NLinear/ETTm1.py --gpus '0'
python experiments/train.py -c baselines/NLinear/ETTm2.py --gpus '0'
python experiments/train.py -c baselines/NLinear/Electricity.py --gpus '0'
python experiments/train.py -c baselines/NLinear/ExchangeRate.py --gpus '0'
python experiments/train.py -c baselines/NLinear/Weather.py --gpus '0'
python experiments/train.py -c baselines/NLinear/PEMS04.py --gpus '0'
python experiments/train.py -c baselines/NLinear/PEMS08.py --gpus '0'
