#!/bin/bash
# python experiments/train.py -c baselines/DeepAR/METR-LA.py --gpus '0'
# python experiments/train.py -c baselines/DeepAR/PEMS-BAY.py --gpus '0'
# python experiments/train.py -c baselines/DeepAR/PEMS03.py --gpus '0'
# python experiments/train.py -c baselines/DeepAR/PEMS04.py --gpus '0'
# python experiments/train.py -c baselines/DeepAR/PEMS07.py --gpus '0'
# python experiments/train.py -c baselines/DeepAR/PEMS08.py --gpus '0'

# python experiments/train.py -c baselines/DeepAR/ETTh1.py --gpus '0'
# python experiments/train.py -c baselines/DeepAR/ETTm1.py --gpus '0'
python experiments/train.py -c baselines/DeepAR/Electricity.py --gpus '0'
python experiments/train.py -c baselines/DeepAR/Weather.py --gpus '0'
python experiments/train.py -c baselines/DeepAR/ExchangeRate.py --gpus '0'
python experiments/train.py -c baselines/DeepAR/PEMS04_LTSF.py --gpus '0'
python experiments/train.py -c baselines/DeepAR/PEMS08_LTSF.py --gpus '0'