#!/bin/bash
python experiments/train.py -c baselines/Pyraformer/ETTh1.py --gpus '0'
python experiments/train.py -c baselines/Pyraformer/ETTh2.py --gpus '0'
python experiments/train.py -c baselines/Pyraformer/ETTm1.py --gpus '0'
python experiments/train.py -c baselines/Pyraformer/ETTm2.py --gpus '0'
python experiments/train.py -c baselines/Pyraformer/Electricity.py --gpus '0'
python experiments/train.py -c baselines/Pyraformer/ExchangeRate.py --gpus '0'
python experiments/train.py -c baselines/Pyraformer/Weather.py --gpus '0'
python experiments/train.py -c baselines/Pyraformer/PEMS04.py --gpus '0'
python experiments/train.py -c baselines/Pyraformer/PEMS08.py --gpus '0'
