#!/bin/bash
python experiments/train.py -c baselines/Crossformer/ETTh1.py --gpus '0'
python experiments/train.py -c baselines/Crossformer/ETTh2.py --gpus '0'
python experiments/train.py -c baselines/Crossformer/ETTm1.py --gpus '0'
python experiments/train.py -c baselines/Crossformer/ETTm2.py --gpus '0'
python experiments/train.py -c baselines/Crossformer/Electricity.py --gpus '0'
python experiments/train.py -c baselines/Crossformer/ExchangeRate.py --gpus '0'
python experiments/train.py -c baselines/Crossformer/Weather.py --gpus '0'
python experiments/train.py -c baselines/Crossformer/PEMS04.py --gpus '0'
python experiments/train.py -c baselines/Crossformer/PEMS08.py --gpus '0'
