#!/bin/bash
python experiments/train.py -c baselines/PatchTST/ETTh1.py --gpus '0'
python experiments/train.py -c baselines/PatchTST/ETTh2.py --gpus '0'
python experiments/train.py -c baselines/PatchTST/ETTm1.py --gpus '0'
python experiments/train.py -c baselines/PatchTST/ETTm2.py --gpus '0'
python experiments/train.py -c baselines/PatchTST/Electricity.py --gpus '0'
python experiments/train.py -c baselines/PatchTST/ExchangeRate.py --gpus '0'
python experiments/train.py -c baselines/PatchTST/Weather.py --gpus '0'
python experiments/train.py -c baselines/PatchTST/PEMS04.py --gpus '0'
python experiments/train.py -c baselines/PatchTST/PEMS08.py --gpus '0'
