#!/bin/bash
python experiments/train.py -c baselines/NBeats/METR-LA.py --gpus '1'
python experiments/train.py -c baselines/NBeats/PEMS-BAY.py --gpus '1'
python experiments/train.py -c baselines/NBeats/PEMS03.py --gpus '1'
python experiments/train.py -c baselines/NBeats/PEMS04.py --gpus '1'
python experiments/train.py -c baselines/NBeats/PEMS07.py --gpus '1'
python experiments/train.py -c baselines/NBeats/PEMS08.py --gpus '1'

python experiments/train.py -c baselines/NBeats/ETTh1.py --gpus '1'
python experiments/train.py -c baselines/NBeats/ETTm1.py --gpus '1'
python experiments/train.py -c baselines/NBeats/Electricity.py --gpus '1'
python experiments/train.py -c baselines/NBeats/Weather.py --gpus '1'
python experiments/train.py -c baselines/NBeats/ExchangeRate.py --gpus '1'
python experiments/train.py -c baselines/NBeats/PEMS04_LTSF.py --gpus '1'
python experiments/train.py -c baselines/NBeats/PEMS08_LTSF.py --gpus '1'
