#!/bin/bash
python experiments/train.py -c baselines/Informer/ETTh1.py --gpus '0'
python experiments/train.py -c baselines/Informer/ETTh2.py --gpus '0'
python experiments/train.py -c baselines/Informer/ETTm1.py --gpus '0'
python experiments/train.py -c baselines/Informer/ETTm2.py --gpus '0'
python experiments/train.py -c baselines/Informer/Electricity.py --gpus '0'
python experiments/train.py -c baselines/Informer/ExchangeRate.py --gpus '0'
python experiments/train.py -c baselines/Informer/Weather.py --gpus '0'
python experiments/train.py -c baselines/Informer/PEMS04.py --gpus '0'
python experiments/train.py -c baselines/Informer/PEMS08.py --gpus '0'
